apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: application-sample-1
    appstudio.openshift.io/component: component-sample-1
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: component-sample-1
  namespace: maysun
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_devfile-samples_devfile-sample-java-springboot-basic
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/devfile-samples/devfile-sample-java-springboot-basic
